### ISSUE TITLE
Bedingte Formatierung in der entgültigen Dispatch Tabelle falsch

### ISSUE THREAD

**Issue by Aeraxon** [rentasad/FTW-Dispatcher#13]
![grafik](https://user-images.githubusercontent.com/117484794/202497185-a02bbd80-d740-4ce9-9509-0b0dc4ded6ea.png)

Hier sollte die 200 als legal markiert sein, sie ist aber rot. vermutlich "kleiner oder gleich"-Problem?

**Comment by Aeraxon** [comment]
In allen Bedingten Formatierungen steht "oder gleich"

**Comment by rentasad** [comment]
Ist repariert in 95b57d175482ad51da387f53bcd08c6a2499813c
