### ISSUE TITLE
Exportierte Dispatching Datei hat unsichere Verknpfungen

### ISSUE THREAD

**Issue by Aeraxon** [rentasad/FTW-Dispatcher#14]
Die exportierte Dispatching Excel hat irgendwelche als unsicher eingestuften Verknüpfungen. Kann man das bereinigen? Soll ja eigentlich nur eine für sich alleinstehende autake Excel sein.

Auch ist sie sehr langsam in der Bearbeitung, das könnte vielleicht miteinander zutun haben.

**Comment by rentasad** [comment]
Ja - ich muss das nochmal prüfen - ich hatte sie schon mal "Verknüpfungsfrei" - hoffe das kriege ich auch wieder so hin :-) Halte Dich auf dem Laufenden.

**Comment by rentasad** [comment]
Wurde hoffentlich repariert in 65474e410154da5bda7ba479289ec599e0076bd1

**Comment by rentasad** [comment]
Fixed in  5edcb1b45f054e9f22f68d5e057deab2a1f4f474
Es gab noch einen Bug.
