### ISSUE TITLE
Long Range Planes - low Distances need to go red

### ISSUE THREAD

**Issue by Aeraxon** [rentasad/FTW-Dispatcher#2]
Wenn ein Flieger ein Langstreckenflieger ist (Long Range = yes), dann müssen distances unter 500 nm rot werden.

**Comment by Aeraxon** [comment]
Hier ist die Formel um alles in einem Feld abzufragen - Kommt aber 0 oder 1 raus

=WENN(UND([@[DISTANCE NM]]<500;PIVOTDATENZUORDNEN("Summe von Long Range Plane?";$J$1)=1);0;WENN([@[TERMINAL PAX]]<PIVOTDATENZUORDNEN("Summe von Seats (manual insert)";$J$1);0;WENN([@[LONGEST RUNWAY]]<PIVOTDATENZUORDNEN("Summe von Min Rwy (m)";$J$1);0;WENN([@[DISTANCE NM]]>PIVOTDATENZUORDNEN("Summe von Max Range (nm)";$J$1);0;1))))

**Comment by rentasad** [comment]
Die funktioniert in der aktuellen Version noch nicht - vermutlich muss ich dafür die anderen ValidSpalten vorher rauslöschen oder?

**Comment by rentasad** [comment]
Ja muss ich :-)
